<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BHoM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\BHoM.dll</HintPath>
    </Reference>
    <Reference Include="BHoM_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\BHoM_Engine.dll</HintPath>
    </Reference>
    <Reference Include="CodeComplianceTest_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\CodeComplianceTest_oM.dll</HintPath>
    </Reference>
    <Reference Include="Test_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Test_Engine.dll</HintPath>
    </Reference>
    <Reference Include="Test_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Test_oM.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
