name: .NET Format
description: Validates code formatting using dotnet format

inputs:
  dotnet-version:
    description: .NET SDK version
    default: '8.x'

  working-directory:
    description: Path to the solution/project root
    default: "."

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v47
      with:
        files: '**/*.cs'

    - name: Debug changed files
      shell: bash
      run: |
        echo "Any Changed ${{ steps.changed-files.outputs.any_changed_files }}"
        echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"

    - name: Check formatting
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        declare -A projects

        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          dir=$(dirname "$file")
          while [[ "$dir" != "." && "$dir" != "/" ]]; do
            csproj=$(find "$dir" -maxdepth 1 -name "*.csproj" | head -1)
            if [ -n "$csproj" ]; then
              projects["$csproj"]=1
              break
            fi
            dir=$(dirname "$dir")
          done
        done

        for csproj in "${!projects[@]}"; do
          echo "Checking formatting for $csproj"
          dotnet format --verify-no-changes --verbosity diagnostic --include ${{ steps.changed-files.outputs.all_changed_files }}
        done