name: .NET Format
description: Validates code formatting using dotnet format

inputs:
  dotnet-version:
    description: .NET SDK version
    default: '8.x'

  working-directory:
    description: Path to the solution/project root
    default: "."

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v47
      with:
        files: '**/*.cs'

    - name: Check formatting
      if: steps.changed-files.outputs.all_changed_files == true
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run:
        dotnet format --verify-no-changes --verbosity diagnostic --include ${{ steps.changed-files.outputs.all_changed_files }}
