<#
.SYNOPSIS
    Build all dependency repositories in the correct order and collect resulting DLLs.

.DESCRIPTION
    This script:
      - Reads deps/_order.txt created by Resolve-DependencyGraph.ps1
      - Restores packages for each repo (NuGet or dotnet)
      - Builds each repo (solution-first, then fallback to csproj)
      - Collects built DLLs into deps-assemblies/
      - Does NOT fail the pipeline on individual repo failures (legacy behaviour)

.INPUTS
    CONFIGURATION env variable (Release / Debug)

.OUTPUTS
    deps-assemblies/*.dll

.NOTES
    If deps/_order.txt is missing, the script falls back to "directory enumeration" i.e.
    it simply builds ALL subdirectories under deps/, in alphabetical order.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$depsDir  = "deps"
$orderOut = Join-Path $depsDir "_order.txt"
$overallFailures = @()

# Determine build order from _order.txt, which is generated by Resolve-DependencyGraph.ps1.
if (-not (Test-Path $orderOut)) {
    Write-Warning "No build order file found; falling back to directory enumeration."
    $order = (Get-ChildItem $depsDir -Directory | Select-Object -ExpandProperty Name)
} else {
    $order = Get-Content $orderOut
}

# Main build loop for each repo in order
foreach ($repoName in $order) {
    $repoPath = Join-Path $depsDir $repoName
    if (-not (Test-Path $repoPath)) { continue }

    Write-Host "::group::Building $repoName"

    # Detect .sln and whether the repo uses packages.config (legacy) or PackageReference (SDK-style)
    $solution = Get-ChildItem $repoPath -Recurse -Filter *.sln -ErrorAction SilentlyContinue | Select-Object -First 1
    $usesPackagesConfig = (Get-ChildItem $repoPath -Recurse -Filter packages.config -ErrorAction SilentlyContinue | Measure-Object).Count -gt 0

    try {
        if ($null -ne $solution) {

            # solution-level restore
            if ($usesPackagesConfig) {
                # Legacy v2 restore path
                nuget restore $solution.FullName -NonInteractive
            } else {
                dotnet restore $solution.FullName
            }
            dotnet build $solution.FullName -c $env:CONFIGURATION --no-restore --nologo -m
        }
        else {

            # No solution: fallback to .csproj-build
            $projects = Get-ChildItem $repoPath -Recurse -Filter *.csproj -ErrorAction SilentlyContinue
            
            if ($projects.Count -eq 0) {
                Write-Host "No .sln or .csproj in $repoName — skipping build."
            } else {
                foreach ($p in $projects) {
                    if ($usesPackagesConfig) {
                        nuget restore $repoPath -NonInteractive
                    } else {
                        dotnet restore $p.FullName
                    }
                    dotnet build $p.FullName -c $env:CONFIGURATION --no-restore --nologo -m
                }
            }
        }
    }
    catch {
        Write-Warning "Build FAILED for '$repoName': $($_.Exception.Message)"
        $overallFailures += "$repoName"
    }

    Write-Host "::endgroup::"
}

# Collect built DLLs into deps-assemblies/
if (-not (Test-Path "deps-assemblies")) {
    New-Item -ItemType Directory -Force -Path "deps-assemblies" | Out-Null
}

Get-ChildItem "deps" -Recurse -Filter *.dll -ErrorAction SilentlyContinue |
  Where-Object { $_.FullName -match "\\bin\\$($env:CONFIGURATION)\\" } |
  ForEach-Object { Copy-Item $_.FullName "deps-assemblies" -Force }

Write-Host "Collected assemblies (sample):"
Get-ChildItem "deps-assemblies" -Filter *.dll -ErrorAction SilentlyContinue |
  Sort-Object Name |
  Select-Object -First 60 |
  ForEach-Object { $_.Name }

# Optionally fail the pipeline if any repo builds failed (legacy behaviour was to ignore failures)
# if ($overallFailures.Count -gt 0) {
#   Write-Error ("One or more dependency builds failed:`n - " + ($overallFailures -join "`n - "))
# }