name: Static Checks

on:
  workflow_call:
    inputs:
      dotnet_version:
        type: string
        required: false
      working_directory:
        type: string
        required: false

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Run .NET Format
          uses: BuroHappoldEngineeringSandbox/DevOps_Toolkit/.github/actions/dotnet-format@main
          with:
            dotnet-version: ${{ inputs.dotnet_version || '8.x' }}
            working-directory: ${{ inputs.working_directory || '.' }}